services:
  db:
    image: postgres:15
    container_name: fleet-db
    environment:
      POSTGRES_USER: fleet_user
      POSTGRES_PASSWORD: fleet_pass
      POSTGRES_DB: fleet_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fleet_user"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
